### ISSUE TITLE
Supported Agda versions

### ISSUE THREAD

**Issue by wenkokke** [lclem/agda-kernel#10]
What versions of Agda does the kernel support? It seems that it doesn't work with the current release candidate.

**Comment by lclem** [comment]
I've been using it with 2.6.0, I will check whether it works with more recent versions

**Comment by lclem** [comment]
it works on 2.6.1. BTW there was a typo in kernel.py, I fixed it now :)

**Comment by wenkokke** [comment]
@lclem Ah, thanks!

**Comment by zampino** [comment]
> What versions of Agda does the kernel support? 

Hi @wenkokke @lclem,

Should also be fine with `Agda-2.6.1.2` which is what we're building in our [Agda environment on Nextjournal](https://nextjournal.com/nextjournal/agda-environment#setup). It didn't propagate as default in our Agda notebooks yet but will soon. We're actually using a fork, but the communication protocol with Agda is the same.

Cheers,
Andrea
