### ISSUE TITLE
Completion Issues (Give instead of Case Split)

### ISSUE THREAD

**Issue by zampino** [lclem/agda-kernel#6]
@lclem let me first thank you for your work on the kernel, we're trying to use it at [nextjournal](https://nextjournal.com/nextjournal/agda-template) to get Agda running.

Using the kernel I've encountered some issues with Tab completions:

1. `Give` command is [always accepted if the provided expression type-checks alright](https://github.com/lclem/agda-kernel/blob/1f50272bfef96e4393711055cf2d476157f9feb3/src/agda_kernel/kernel.py#L855-L864), but we might want to trigger a case split instead (as meantioned in the [README](https://github.com/lclem/agda-kernel#functionality)) like in this case:

![missing-case-split](https://user-images.githubusercontent.com/1078464/67310763-aa725180-f4fe-11e9-9338-8e2c560067e0.gif)

2. suggestions from agsy involving chains of eq-reasoning are split erroneously

<img width="702" alt="Screenshot 2019-10-22 at 18 50 46" src="https://user-images.githubusercontent.com/1078464/67311190-6a5f9e80-f4ff-11e9-8a9a-f2912fcc334a.png">

From logs I understand it's a matter of [splitting response lines](https://github.com/lclem/agda-kernel/blob/1f50272bfef96e4393711055cf2d476157f9feb3/src/agda_kernel/kernel.py#L834-L841) from agsy: 
```
[IPKernelApp] ERROR | result is: Listing solution(s) 0-9
0  cong suc (+-assoc m n p)
1  begin
suc (m + n + p) ≡⟨ cong suc (+-assoc m n p) ⟩
suc (m + (n + p)) ≡⟨
sym (cong (λ _ → suc (m + (n + p))) (+-assoc m p p)) ⟩
suc (m + (n + p)) ∎
2  begin
suc (m + n + p) ≡⟨ cong suc (+-assoc m n p) ⟩
suc (m + (n + p)) ≡⟨
sym (cong (λ _ → suc (m + (n + p))) (+-assoc m p n)) ⟩
suc (m + (n + p)) ∎
3  begin
suc (m + n + p) ≡⟨ cong suc (+-assoc m n p) ⟩
suc (m + (n + p)) ≡⟨
sym (cong (λ _ → suc (m + (n + p))) (+-assoc m p m)) ⟩
suc (m + (n + p)) ∎
4  begin .....
```

Given it is hard to map the whole [agda-mode](https://agda.readthedocs.io/en/v2.6.0.1/tools/emacs-mode.htmll) onto just two commands (Tab and Shift+Tab) do you have suggestions on how to solve 1. (while for 2. I probably can open a pull request for a fix). Would it make sense to _always prefer_ `AGDA_CMD_MAKE_CASE` command in case the expression in the hole isn't empty and the case command succeeds? (Returning both the result of _give_ and _case split_ might mess up cursor start/end for substitution in the client).

Do you think we could handle case split over agsy? Do you know if it's possible to pass [agsy  options](https://agda.readthedocs.io/en/v2.6.0.1/tools/auto.html#usage) directly into the hole? Something like `{! -c m !}` in the context of the first example above to trigger case split.

You can [remix this nextjournal notebook](https://nextjournal.com/zampino/agda-kernel-issues) to reproduce the issues above.

**Comment by lclem** [comment]
Thank you for your work in using this kernel in the nextjournal project!
It has the potential of spreading Agda to a larger user base :)

Regarding 1., I don't think doing AGDA_CMD_MAKE_CASE would make sense in every situation.
One solution is to return two options, the first one is to do the case split, and the second one is to close the hole, and let the user decide; as you noted, doing this naively does not work, but one could return the minimal common context required by all the options, not so elegant though.

Regarding Agsy, currently I always pass the options "-m -l" (to get a list of different solutions).
It would be difficult to handle holes of the form "{! -c m !}" since in general "-c m" is a legitimate Agda term (!) and this could mess up some (corner) cases.

Regarding 2., it's indeed just a bug, so please go ahead and open a pull request :)

**Comment by zampino** [comment]
> One solution is to return two options, the first one is to do the case split, and the second one is to close the hole

I agree this would be the best scenario. 

> one could return the minimal common context required by all the options

while nextjournal supports completion items as dicts, each one carrying its own replacement range along with the replacement text, I'm not sure this is now supported by the Jupyter specification.

>  please go ahead and open a pull request

Sure, hope to find the time soon!

**Comment by lclem** [comment]
> > One solution is to return two options, the first one is to do the case split, and the second one is to close the hole
> 
> I agree this would be the best scenario.
> 
> > one could return the minimal common context required by all the options
> 
> while nextjournal supports completion items as dicts, each one carrying its own replacement range along with the replacement text, I'm not sure this is supported by the Jupyter specification yet.
> 
> > please go ahead and open a pull request
> 
> Sure, hope to find the time soon!

no worries, I figured I could do it rather quickly, this is solved now :)

**Comment by lclem** [comment]
it remains to address the original issue of give vs. case split

**Comment by lclem** [comment]
> > > One solution is to return two options, the first one is to do the case split, and the second one is to close the hole
> > 
> > 
> > I agree this would be the best scenario.
> > > one could return the minimal common context required by all the options
> > 
> > 
> > while nextjournal supports completion items as dicts, each one carrying its own replacement range along with the replacement text, I'm not sure this is supported by the Jupyter specification yet.

Jupyter does not support this at this point,
however since the change required would be quite localized,
one could have a modified Agda kernel for nextjournal which would make this feature available;
if in the future Jupyter would adopt such an extension, then the two kernels could be merged.

> > > please go ahead and open a pull request
> > 
> > 
> > Sure, hope to find the time soon!
> 
> no worries, I figured I could do it rather quickly, this is solved now :)

**Comment by zampino** [comment]
> one could have a modified Agda kernel for nextjournal which would make this feature available

Yes, I'll make give + split suggestions in our fork and thanks for the fix!
